Development
300ms/Bubble-Sort pull request #2
Opened 2019-11-20 21:54 UTC by 300ms

Waiting for a code review

2019-11-20 23:09 UTC, stratospherique requested changes
### Great Progress :clap: However, further changes needs to be applied in order to get approval for this project. check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your code :nerd_face: 

- **[REQUIRED]** Fix linter checks errors, I included a suggestion in the code comments. They should be helpful.

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2019-11-20 23:09 UTC, stratospherique commented on bubble_sort.rb
> +    x = 0
- You can use each block in this manner 
```ruby
    arr.each |item| do
        # logic
    end
```

2019-11-20 23:09 UTC, stratospherique commented on bubble_sort.rb
> +end
* [ ] bubble_sort_by raises an error if block is not given. 
- **[HINT]** Check for `block_given?` at the beginning of the method and raise an error if no block was passed.

2019-11-21 16:32 UTC, maelfosso approved these changes
# Congratulations :clap: You did it :smile: 

You can merge it :+1: 
Good luck with the next project

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-11-21 18:04 UTC, merged